name: Build Xenia Mac
on:
  workflow_dispatch:
  push:
    branches: [ "fix-metal-text-swizzle" ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        brew install sdl2

    - name: The FFmpeg Nuke (Bypass Audio/Architecture Crashes)
      run: |
        sed -i '' '/"libavcodec",/d' src/xenia/gpu/metal/premake5.lua
        sed -i '' '/"libavcodec",/d' src/xenia/app/premake5.lua
        sed -i '' '/"libavutil",/d' src/xenia/gpu/metal/premake5.lua
        sed -i '' '/"libavutil",/d' src/xenia/app/premake5.lua
        sed -i '' '/"third_party\/FFmpeg"/d' premake5.lua
        sed -i '' 's/return std::make_unique<FFmpegVideoDecoder>();/return nullptr;/g' src/xenia/emulator.cc
        touch third_party/FFmpeg/premake5.lua

    - name: Setup Premake
      run: |
        python3 xenia-build.py setup

    - name: Force Xcode Intel Compile (x86_64 + AVX)
      run: |
        cd build
        xcodebuild -workspace xenia.xcworkspace -configuration Debug -scheme xenia-app ONLY_ACTIVE_ARCH=NO VALID_ARCHS="x86_64" ARCHS="x86_64" -destination 'generic/platform=macOS,name=Any Mac' OTHER_CPLUSPLUSFLAGS='$(inherited) -mavx -mavx2' OTHER_CFLAGS='$(inherited) -mavx -mavx2'

    - name: Upload Compiled App
      uses: actions/upload-artifact@v4
      with:
        name: Xenia-Canary-Mac-App
        path: build/bin/
